baseURL = "https://slinviz.github.io/"
languageCode = "en-us"
title = "Lin's Hugo Site"
theme = "Ananke"

[params.social]
  rss = true
  email = "slinviz@gmail.com"
  github = "https://github.com/slinviz"
